# Álgebra lineal

Enlace recomendado:

[Quantitative Economics with Julia](http://quant-econ.net/_static/pdfs/jl-quant-econ.pdf)

In [1]:
a = [10, 20, 30, 40]

4-element Array{Int64,1}:
 10
 20
 30
 40

In [2]:
ndims(a)

1

In [3]:
size(a)

(4,)

In [13]:
?ndims

search: ndims RoundingMode invdigamma ENDIAN_BOM



```
ndims(A) -> Integer
```

Returns the number of dimensions of `A`


In [5]:
eye(3)

3x3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [6]:
size(ans)

(3,3)

In [7]:
Array{Int64,1} == Vector{Int64}

true

In [8]:
Array{Int64,2} == Matrix{Int64}

true

In [9]:
Array{Int64,3} == Matrix{Int64}

false

In [10]:
a = [10,20,30, 40]

4-element Array{Int64,1}:
 10
 20
 30
 40

In [13]:
b = reshape(a,2,2)

2x2 Array{Int64,2}:
 10  30
 20  40

In [14]:
b[1,1]

10

In [15]:
b[1,1] = 100

100

In [16]:
b

2x2 Array{Int64,2}:
 100  30
  20  40

In [22]:
a = [1.,2.,3.,4]

4-element Array{Float64,1}:
 1.0
 2.0
 3.0
 4.0

In [23]:
transpose(transpose(a))

4x1 Array{Float64,2}:
 1.0
 2.0
 3.0
 4.0

In [24]:
a'

1x4 Array{Float64,2}:
 1.0  2.0  3.0  4.0

In [18]:
a = [1. 2. 3. 4.]

1x4 Array{Float64,2}:
 1.0  2.0  3.0  4.0

In [19]:
transpose(a)

4x1 Array{Float64,2}:
 1.0
 2.0
 3.0
 4.0

## Algunos comandos para inicializar arreglos

In [25]:
eye(2)

2x2 Array{Float64,2}:
 1.0  0.0
 0.0  1.0

In [28]:
ones(2,2,2)

2x2x2 Array{Float64,3}:
[:, :, 1] =
 1.0  1.0
 1.0  1.0

[:, :, 2] =
 1.0  1.0
 1.0  1.0

In [29]:
fill(35,2,2)

2x2 Array{Int64,2}:
 35  35
 35  35

In [30]:
a = [10 20; 30 40]

2x2 Array{Int64,2}:
 10  20
 30  40

In [31]:
transpose(a)

2x2 Array{Int64,2}:
 10  30
 20  40

In [32]:
a'

2x2 Array{Int64,2}:
 10  30
 20  40

In [33]:
1:9

1:9

In [34]:
typeof(ans)

UnitRange{Int64}

In [35]:
b = collect(1:9)

9-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

In [36]:
b

9-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

In [37]:
?collect

search: collect Collections



```
collect(collection)
```

Return an array of all items in a collection. For associative collections, returns Pair{KeyType, ValType}.

```
collect(element_type, collection)
```

Return an array of type `Array{element_type,1}` of all items in a collection.


In [38]:
1:2:9

1:2:9

In [39]:
typeof(ans)

StepRange{Int64,Int64}

In [40]:
a = collect(1:2:9)

5-element Array{Int64,1}:
 1
 3
 5
 7
 9

In [41]:
a = [10 20; 30 40]

2x2 Array{Int64,2}:
 10  20
 30  40

In [45]:
a[:,1]

2-element Array{Int64,1}:
 10
 30

In [46]:
a[1,:]

1x2 Array{Int64,2}:
 10  20

# Métodos sobre arreglos

In [1]:
a = [-1, 0, 1]

3-element Array{Int64,1}:
 -1
  0
  1

In [2]:
length(a)

3

In [3]:
?length

search: length



```
length(collection) -> Integer
```

For ordered, indexable collections, the maximum index `i` for which `getindex(collection, i)` is valid. For unordered collections, the number of elements.

```
length(s)
```

The number of characters in string `s`.

```
length(A) -> Integer
```

Returns the number of elements in `A`.


In [4]:
sum(a)

0

In [5]:
mean(a)

0.0

In [6]:
std(a)

1.0

In [7]:
var(a)

1.0

In [8]:
maximum(a)

1

In [9]:
minimum(a)

-1

In [10]:
sort(a)

3-element Array{Int64,1}:
 -1
  0
  1

In [57]:
b = sort(a, rev = true)

3-element Array{Int64,1}:
  1
  0
 -1

In [11]:
?sort

search: sort sort! sortrows sortperm sortcols sortperm! Cshort issorted



```
sort(A, dim, [alg=<algorithm>,] [by=<transform>,] [lt=<comparison>,] [rev=false])
```

Sort a multidimensional array `A` along the given dimension.

```
sort(v, [alg=<algorithm>,] [by=<transform>,] [lt=<comparison>,] [rev=false])
```

Variant of `sort!` that returns a sorted copy of `v` leaving `v` itself unmodified.


In [12]:
a

3-element Array{Int64,1}:
 -1
  0
  1

In [13]:
sort!(a, rev = true)

3-element Array{Int64,1}:
  1
  0
 -1

In [14]:
a

3-element Array{Int64,1}:
  1
  0
 -1

In [15]:
a = ones(1,2)

1x2 Array{Float64,2}:
 1.0  1.0

In [16]:
b = ones(2,2)

2x2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

In [18]:
b * a

LoadError: LoadError: DimensionMismatch("A has dimensions (2,2) but B has dimensions (1,2)")
while loading In[18], in expression starting on line 1

In [21]:
@which a * b

*{T,S}(A::AbstractArray{T,2}, B::Union{DenseArray{S,2},SubArray{S,2,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}}) at linalg/matmul.jl:131

In [20]:
methods(*)

# 138 methods for generic function "*":
*(x::Bool, y::Bool) at bool.jl:38
*{T<:Unsigned}(x::Bool, y::T<:Unsigned) at bool.jl:53
*(x::Bool, z::Complex{Bool}) at complex.jl:122
*(x::Bool, z::Complex{T<:Real}) at complex.jl:129
*{T<:Number}(x::Bool, y::T<:Number) at bool.jl:49
*(x::Float32, y::Float32) at float.jl:211
*(x::Float64, y::Float64) at float.jl:212
*(z::Complex{T<:Real}, w::Complex{T<:Real}) at complex.jl:113
*(z::Complex{Bool}, x::Bool) at complex.jl:123
*(z::Complex{T<:Real}, x::Bool) at complex.jl:130
*(x::Real, z::Complex{Bool}) at complex.jl:140
*(z::Complex{Bool}, x::Real) at complex.jl:141
*(x::Real, z::Complex{T<:Real}) at complex.jl:152
*(z::Complex{T<:Real}, x::Real) at complex.jl:153
*(x::Rational{T<:Integer}, y::Rational{T<:Integer}) at rational.jl:186
*(a::Float16, b::Float16) at float16.jl:136
*{N}(a::Integer, index::CartesianIndex{N}) at multidimensional.jl:50
*(x::BigInt, y::BigInt) at gmp.jl:256
*(a::BigInt, b::BigInt, c::BigInt) at gmp.jl:279
*(a::BigInt, b::BigInt, c::BigInt, d::BigInt) at gmp.jl:285
*(a::BigInt, b::BigInt, c::BigInt, d::BigInt, e::BigInt) at gmp.jl:292
*(x::BigInt, c::Union{UInt16,UInt32,UInt64,UInt8}) at gmp.jl:326
*(c::Union{UInt16,UInt32,UInt64,UInt8}, x::BigInt) at gmp.jl:330
*(x::BigInt, c::Union{Int16,Int32,Int64,Int8}) at gmp.jl:332
*(c::Union{Int16,Int32,Int64,Int8}, x::BigInt) at gmp.jl:336
*(x::BigFloat, y::BigFloat) at mpfr.jl:208
*(x::BigFloat, c::Union{UInt16,UInt32,UInt64,UInt8}) at mpfr.jl:215
*(c::Union{UInt16,UInt32,UInt64,UInt8}, x::BigFloat) at mpfr.jl:219
*(x::BigFloat, c::Union{Int16,Int32,Int64,Int8}) at mpfr.jl:223
*(c::Union{Int16,Int32,Int64,Int8}, x::BigFloat) at mpfr.jl:227
*(x::BigFloat, c::Union{Float16,Float32,Float64}) at mpfr.jl:231
*(c::Union{Float16,Float32,Float64}, x::BigFloat) at mpfr.jl:235
*(x::BigFloat, c::BigInt) at mpfr.jl:239
*(c::BigInt, x::BigFloat) at mpfr.jl:243
*(a::BigFloat, b::BigFloat, c::BigFloat) at mpfr.jl:379
*(a::BigFloat, b::BigFloat, c::BigFloat, d::BigFloat) at mpfr.jl:385
*(a::BigFloat, b::BigFloat, c::BigFloat, d::BigFloat, e::BigFloat) at mpfr.jl:392
*{T<:Number}(x::T<:Number, D::Diagonal{T}) at linalg/diagonal.jl:89
*(x::Irrational{sym}, y::Irrational{sym}) at irrationals.jl:72
*(y::Real, x::Base.Dates.Period) at dates/periods.jl:55
*(x::Number) at operators.jl:74
*(y::Number, x::Bool) at bool.jl:55
*(x::Int8, y::Int8) at int.jl:19
*(x::UInt8, y::UInt8) at int.jl:19
*(x::Int16, y::Int16) at int.jl:19
*(x::UInt16, y::UInt16) at int.jl:19
*(x::Int32, y::Int32) at int.jl:19
*(x::UInt32, y::UInt32) at int.jl:19
*(x::Int64, y::Int64) at int.jl:19
*(x::UInt64, y::UInt64) at int.jl:19
*(x::Int128, y::Int128) at int.jl:456
*(x::UInt128, y::UInt128) at int.jl:457
*{T<:Number}(x::T<:Number, y::T<:Number) at promotion.jl:212
*(x::Number, y::Number) at promotion.jl:168
*{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},S}(A::Union{DenseArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2},SubArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}}, x::Union{DenseArray{S,1},SubArray{S,1,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}}) at linalg/matmul.jl:82
*(A::SymTridiagonal{T}, B::Number) at linalg/tridiag.jl:86
*(A::Tridiagonal{T}, B::Number) at linalg/tridiag.jl:406
*(A::UpperTriangular{T,S<:AbstractArray{T,2}}, x::Number) at linalg/triangular.jl:454
*(A::Base.LinAlg.UnitUpperTriangular{T,S<:AbstractArray{T,2}}, x::Number) at linalg/triangular.jl:457
*(A::LowerTriangular{T,S<:AbstractArray{T,2}}, x::Number) at linalg/triangular.jl:454
*(A::Base.LinAlg.UnitLowerTriangular{T,S<:AbstractArray{T,2}}, x::Number) at linalg/triangular.jl:457
*(A::Tridiagonal{T}, B::UpperTriangular{T,S<:AbstractArray{T,2}}) at linalg/triangular.jl:969
*(A::Tridiagonal{T}, B::Base.LinAlg.UnitUpperTriangular{T,S<:AbstractArray{T,2}}) at linalg/triangular.jl:969
*(A::Tridiagonal{T}, B::LowerTriangular{T,S<:AbstractArray{T

In [22]:
b * a'

2x1 Array{Float64,2}:
 2.0
 2.0

In [23]:
b * a

LoadError: LoadError: DimensionMismatch("A has dimensions (2,2) but B has dimensions (1,2)")
while loading In[23], in expression starting on line 1

Consideremos el sistema lineal $A X = B$, la solución formal es $X = A^{-1}B$

In [26]:
big(0.1)

1.000000000000000055511151231257827021181583404541015625000000000000000000000000e-01

In [27]:
typeof(big(0.1))

BigFloat

In [28]:
A = [big(1.) 2; 2 3]

2x2 Array{BigFloat,2}:
 1.000000000000000000000000000000000000000000000000000000000000000000000000000000  …  2.000000000000000000000000000000000000000000000000000000000000000000000000000000
 2.000000000000000000000000000000000000000000000000000000000000000000000000000000     3.000000000000000000000000000000000000000000000000000000000000000000000000000000

In [29]:
B = ones(2,2)

2x2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

In [30]:
X = inv(A)*B

2x2 Array{BigFloat,2}:
 -1.000000000000000000000000000000000000000000000000000000000000000000000000000000  …  -1.000000000000000000000000000000000000000000000000000000000000000000000000000000
  1.000000000000000000000000000000000000000000000000000000000000000000000000000000      1.000000000000000000000000000000000000000000000000000000000000000000000000000000

In [31]:
A*X

2x2 Array{BigFloat,2}:
 1.000000000000000000000000000000000000000000000000000000000000000000000000000000  …  1.000000000000000000000000000000000000000000000000000000000000000000000000000000
 1.000000000000000000000000000000000000000000000000000000000000000000000000000000     1.000000000000000000000000000000000000000000000000000000000000000000000000000000

In [35]:
A*X == B

true

In [36]:
a = [1., 2., 4]

3-element Array{Float64,1}:
 1.0
 2.0
 4.0

In [40]:
b = [3.,4.]

2-element Array{Float64,1}:
 3.0
 4.0

In [41]:
dot(a, b)

LoadError: LoadError: DimensionMismatch("dot product arguments have lengths 3 and 2")
while loading In[41], in expression starting on line 1

In [39]:
a ⋅ b

31.0

**Tarea** Crea una función que se llame producto punto y realice algo similar a dot

In [87]:
a

3-element Array{Float64,1}:
 1.0
 2.0
 4.0

In [88]:
a * 2

3-element Array{Float64,1}:
 2.0
 4.0
 8.0

In [89]:
a + 2

3-element Array{Float64,1}:
 3.0
 4.0
 6.0

In [90]:
a > 1

LoadError: LoadError: MethodError: `isless` has no method matching isless(::Int64, ::Array{Float64,1})
Closest candidates are:
  isless(::Real, !Matched::AbstractFloat)
  isless(::Real, !Matched::Real)
  isless(::Integer, !Matched::Char)
while loading In[90], in expression starting on line 1

In [91]:
a .> 1

3-element BitArray{1}:
 false
  true
  true

In [92]:
log(a)

3-element Array{Float64,1}:
 0.0     
 0.693147
 1.38629 

In [93]:
A = [1 2; 3 4]

2x2 Array{Int64,2}:
 1  2
 3  4

In [94]:
det(A)

-2.0

In [95]:
trace(A)

5

In [96]:
eigvals(A)

2-element Array{Float64,1}:
 -0.372281
  5.37228 

In [97]:
rank(A)

2