## Sesión 1

Para empezar hay por los menos cuatro recursos buenos 

- [First steps with Julia](http://blog.brakmic.com/first-steps-with-julia/)
- [Learn Julia in Y minutes](https://learnxinyminutes.com/docs/julia/)
- [Introduction to Julia](https://www.youtube.com/watch?v=vWkgEddb4-A)  by David Sanders 
- [Introduction to Julia for Scientific Computing](https://www.youtube.com/watch?v=gQ1y5NUD_RI) by David Sanders

Temas más avanzados:
- [Juia in a nutshell](http://www.agilegeoscience.com/blog/2014/9/4/julia-in-a-nutshell.html)

## Numbers, variables and basic functions

Tarea: Lee la  documentación [Integers and Floating Point numbers](http://docs.julialang.org/en/release-0.4/manual/integers-and-floating-point-numbers/)

In [30]:
a = 3

3

In [32]:
typeof(a)

Int64

In [35]:
b = 3/5

0.6

In [36]:
typeof(b)

Float64

In [38]:
c = 3 //5

3//5

In [39]:
typeof(c)

Rational{Int64}

In [40]:
3//4 + 5//6

19//12

Escribiendo \alpha y después TAB puede usar notación LaTeX

In [2]:
α = 5

5

In [4]:
f(x) = 2x

f (generic function with 1 method)

In [6]:
f(α)

10

Explora los siguientes comandos de julia
   - `typemin`
   - `typemax`
La firma de estos es
   - `typemin(tipo)`
   - `typemax(tipo)`
 
¿Qué crees qué significan? ¿Porqué en ciertos casos un `Inf` es regresado? ¿Significa esto que con **Julia** la computadora puede representar todos los reales?

Define las siguientes dos variables

+ x = 0.1
+ y = 0.5


Aplica la función big sobre estas variables. Interpreta e resultado

In [21]:
x = 0.1
big(x)

1.000000000000000055511151231257827021181583404541015625000000000000000000000000e-01

In [22]:
y = 0.5
big(y)

5.000000000000000000000000000000000000000000000000000000000000000000000000000000e-01

Ahora aplica la función bits e interpreta el resultado

In [24]:
bits(x)

"0011111110111001100110011001100110011001100110011001100110011010"

In [25]:
bits(y)

"0011111111100000000000000000000000000000000000000000000000000000"

## Iteration and ranges 

In [92]:
for i in 1:10
    println(i)
end

1
2
3
4
5
6
7
8
9
10


In [95]:
typeof(1:10)

UnitRange{Int64}

In [96]:
a = 1:10

1:10

In [98]:
for j in a
    println(j)
end

1
2
3
4
5
6
7
8
9
10


In [99]:
for hola in a
    println(hola)
end

1
2
3
4
5
6
7
8
9
10


## Tuples

In [101]:
a = (1, 3)

(1,3)

In [103]:
typeof(a)

Tuple{Int64,Int64}

In [104]:
b = [1, 3]

2-element Array{Int64,1}:
 1
 3

In [105]:
typeof(b)

Array{Int64,1}

## Vectors

In [2]:
v = [1]

1-element Array{Int64,1}:
 1

In [3]:
push!(v,3.5)

LoadError: LoadError: InexactError()
while loading In[3], in expression starting on line 1

In [4]:
w = Any[]

In [5]:
k = Float64[]

In [6]:
b = Array{Float64,1}(3)

3-element Array{Float64,1}:
 6.90291e-310
 6.90291e-310
 6.90291e-310

In [11]:
push!(w,4.0)

1-element Array{Any,1}:
 4.0

In [14]:
push!(w,5)

2-element Array{Any,1}:
 4.0
 5  

In [16]:
a = w

2-element Array{Any,1}:
 4.0
 5  

In [17]:
push!(w, "hola")

3-element Array{Any,1}:
 4.0    
 5      
  "hola"

In [20]:
a

3-element Array{Any,1}:
 4.0    
 5      
  "hola"

In [27]:
Vector{Float64}(10)

10-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [28]:
Vector(10)

10-element Array{Any,1}:
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef

In [108]:
b = [78, 15, 25 ,69, 47, 58, 25 ,31, 45, 72]

10-element Array{Int64,1}:
 78
 15
 25
 69
 47
 58
 25
 31
 45
 72

In [111]:
c = sort(b)

10-element Array{Int64,1}:
 15
 25
 25
 31
 45
 47
 58
 69
 72
 78

In [113]:
c == b

false

In [114]:
sort!(b)

10-element Array{Int64,1}:
 15
 25
 25
 31
 45
 47
 58
 69
 72
 78

In [115]:
c == b

true

In [1]:
? push!

search: push! pushdisplay



```rst
..  push!(collection, items...) -> collection

Insert one or more ``items`` at the end of ``collection``.

.. doctest::

  julia> push!([1, 2, 3], 4, 5, 6)
  6-element Array{Int64,1}:
   1
   2
   3
   4
   5
   6

Use :func:`append!` to add all the elements of another collection to
``collection``.
The result of the preceding example is equivalent to
``append!([1, 2, 3], [4, 5, 6])``.
```


In [2]:
? append!

search: append!



```rst
..  append!(collection, collection2) -> collection.

Add the elements of ``collection2`` to the end of ``collection``.

.. doctest::

   julia> append!([1],[2,3])
   3-element Array{Int64,1}:
    1
    2
    3

.. doctest::

   julia> append!([1, 2, 3], [4, 5, 6])
   6-element Array{Int64,1}:
    1
    2
    3
    4
    5
    6

Use :func:`push!` to add individual items to ``collection`` which are not
already themselves in another collection.
The result is of the preceding example is equivalent to
``push!([1, 2, 3], 4, 5, 6)``.
```


In [3]:
a = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [4]:
b = copy(a)

3-element Array{Int64,1}:
 1
 2
 3

In [5]:
a[3] = 5

5

In [6]:
a == b

false

In [7]:
pointer(a)

Ptr{Int64} @0x00007fd5cf2b9ba0

## Functions


In [8]:

f(x) = 2*x

f (generic function with 1 method)

In [9]:
g(x) = 2.0*x

g (generic function with 1 method)

In [10]:
f(2), g(2)

(4,4.0)

In [11]:
methods(f)

# 1 method for generic function "f":
f(x) at In[8]:2

In [12]:
2^3.0

8.0

In [13]:
methods(^)

# 45 methods for generic function "^":
^(x::Bool, y::Bool) at bool.jl:39
^(x::BigInt, y::Bool) at gmp.jl:430
^(x::Integer, y::Bool) at bool.jl:40
^{T<:AbstractFloat}(z::Complex{T<:AbstractFloat}, p::Complex{T<:AbstractFloat}) at complex.jl:433
^{T<:Complex{T<:Real}}(z::T<:Complex{T<:Real}, p::T<:Complex{T<:Real}) at complex.jl:480
^{T<:AbstractFloat}(z::Complex{T<:AbstractFloat}, n::Bool) at complex.jl:540
^{T<:Integer}(z::Complex{T<:Integer}, n::Bool) at complex.jl:541
^{T<:Rational{T<:Integer}}(z::Complex{T<:Rational{T<:Integer}}, n::Bool) at rational.jl:321
^(z::Complex{T<:Real}, n::Bool) at complex.jl:537
^{T<:AbstractFloat}(z::Complex{T<:AbstractFloat}, n::Integer) at complex.jl:543
^{T<:Integer}(z::Complex{T<:Integer}, n::Integer) at complex.jl:545
^{T<:Rational{T<:Integer}}(z::Complex{T<:Rational{T<:Integer}}, n::Integer) at rational.jl:323
^(z::Complex{T<:Real}, n::Integer) at complex.jl:538
^(x::Rational{T<:Integer}, n::Integer) at rational.jl:314
^{T<:AbstractFloat}(x::T<:AbstractFloat, y::Rational{T<:Integer}) at rational.jl:318
^{T<:AbstractFloat}(x::Complex{T<:AbstractFloat}, y::Rational{T<:Integer}) at rational.jl:319
^(::Irrational{:e}, x::Rational{T<:Integer}) at irrationals.jl:123
^(x::Number, y::Rational{T<:Integer}) at rational.jl:317
^(x::BigInt, y::UInt64) at gmp.jl:404
^(x::BigInt, y::BigInt) at gmp.jl:429
^(x::BigInt, y::Integer) at gmp.jl:431
^(x::Integer, y::BigInt) at gmp.jl:432
^{T<:Integer}(x::T<:Integer, p::T<:Integer) at intfuncs.jl:106
^(x::Float64, y::Integer) at math.jl:278
^(x::Float32, y::Integer) at math.jl:280
^(x::Float16, y::Integer) at float16.jl:163
^(x::BigFloat, y::Union{UInt16,UInt32,UInt64,UInt8}) at mpfr.jl:427
^(x::BigFloat, y::Union{Int16,Int32,Int64,Int8}) at mpfr.jl:433
^(x::BigFloat, y::BigInt) at mpfr.jl:439
^(::Irrational{:e}, x::Integer) at irrationals.jl:123
^(x::Number, p::Integer) at intfuncs.jl:107
^(x::Float64, y::Float64) at math.jl:275
^(x::Float32, y::Float32) at math.jl:276
^(a::Float16, b::Float16) at float16.jl:136
^(x::BigFloat, y::BigFloat) at mpfr.jl:421
^(::Irrational{:e}, x::Irrational{sym}) at irrationals.jl:123
^(x::Irrational{sym}, y::Irrational{sym}) at irrationals.jl:72
^(::Irrational{:e}, x::Number) at irrationals.jl:123
^{T<:Number}(x::T<:Number, y::T<:Number) at promotion.jl:215
^(x::Number, y::Number) at promotion.jl:171
^(s::AbstractString, r::Integer) at strings/types.jl:185
^(A::Array{T,2}, p::Integer) at linalg/dense.jl:172
^(x, p::Integer) at intfuncs.jl:108
^(A::Array{T,2}, p::Number) at linalg/dense.jl:175
^(::Irrational{:e}, x::AbstractArray{T,2}) at irrationals.jl:128

In [14]:
@which 2^3.0

^(x::Number, y::Number) at promotion.jl:171