## Iteration and ranges 

In [92]:
for i in 1:10
    println(i)
end

1
2
3
4
5
6
7
8
9
10


In [96]:
a = 1:10

1:10

In [2]:
typeof(1:10)

UnitRange{Int64}

In [98]:
for j in a
    println(j)
end

1
2
3
4
5
6
7
8
9
10


In [99]:
for hola in a
    println(hola)
end

1
2
3
4
5
6
7
8
9
10


## Tuples

In [101]:
a = (1, 3)

(1,3)

In [103]:
typeof(a)

Tuple{Int64,Int64}

In [104]:
b = [1, 3]

2-element Array{Int64,1}:
 1
 3

In [105]:
typeof(b)

Array{Int64,1}


## Conditionals

## Matrices and vectors

In [2]:
v = [1]

1-element Array{Int64,1}:
 1

In [3]:
push!(v,3.5)

LoadError: LoadError: InexactError()
while loading In[3], in expression starting on line 1

In [4]:
w = Any[]

In [5]:
k = Float64[]

In [6]:
b = Array{Float64,1}(3)

3-element Array{Float64,1}:
 6.90291e-310
 6.90291e-310
 6.90291e-310

In [11]:
push!(w,4.0)

1-element Array{Any,1}:
 4.0

In [14]:
push!(w,5)

2-element Array{Any,1}:
 4.0
 5  

In [16]:
a = w

2-element Array{Any,1}:
 4.0
 5  

In [17]:
push!(w, "hola")

3-element Array{Any,1}:
 4.0    
 5      
  "hola"

In [20]:
a

3-element Array{Any,1}:
 4.0    
 5      
  "hola"

In [27]:
Vector{Float64}(10)

10-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [28]:
Vector(10)

10-element Array{Any,1}:
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef

In [108]:
b = [78, 15, 25 ,69, 47, 58, 25 ,31, 45, 72]

10-element Array{Int64,1}:
 78
 15
 25
 69
 47
 58
 25
 31
 45
 72

In [111]:
c = sort(b)

10-element Array{Int64,1}:
 15
 25
 25
 31
 45
 47
 58
 69
 72
 78

In [113]:
c == b

false

In [114]:
sort!(b)

10-element Array{Int64,1}:
 15
 25
 25
 31
 45
 47
 58
 69
 72
 78

In [115]:
c == b

true

In [125]:
? push!

search: 

```
push!(collection, items...) -> collection
```

Insert one or more `items` at the end of `collection`.

```jldoctest
julia> push!([1, 2, 3], 4, 5, 6)
6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
```

Use [`append!`](:func:`append!`) to add all the elements of another collection to `collection`. The result of the preceding example is equivalent to `append!([1, 2, 3], [4, 5, 6])`.


push! pushdisplay



In [124]:
? append!

search: 

```
append!(collection, collection2) -> collection.
```

Add the elements of `collection2` to the end of `collection`.

```jldoctest
julia> append!([1],[2,3])
3-element Array{Int64,1}:
 1
 2
 3
```

```jldoctest
julia> append!([1, 2, 3], [4, 5, 6])
6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
```

Use [`push!`](:func:`push!`) to add individual items to `collection` which are not already themselves in another collection. The result is of the preceding example is equivalent to `push!([1, 2, 3], 4, 5, 6)`.


append!



In [127]:
a = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [128]:
b = copy(a)

3-element Array{Int64,1}:
 1
 2
 3

In [129]:
a[3] = 5

5

In [132]:
a == b

false

In [134]:
pointer(a)

Ptr{Int64} @0x00007f124ec215c0

## Functions


In [126]:

f(x) = 2*x

In [32]:
g(x) = 2.0*x

g (generic function with 1 method)

In [34]:
f(2), g(2)

(4,4.0)

In [35]:
methods(f)

# 1 method for generic function "f":
f(x) at In[31]:1

In [38]:
2^3.0

8.0

In [39]:
methods(^)

# 25 methods for generic function "^":
^(x::Integer, y::Bool) at bool.jl:40
^{T<:AbstractFloat}(z::Complex{T}, p::Complex{T}) at complex.jl:461
^{T<:Complex{T<:Real}}(z::T, p::T) at complex.jl:508
^{T<:AbstractFloat}(z::Complex{T}, n::Bool) at complex.jl:568
^{T<:Integer}(z::Complex{T}, n::Bool) at complex.jl:569
^{T<:Rational{T<:Integer}}(z::Complex{T}, n::Bool) at rational.jl:361
^(z::Complex, n::Bool) at complex.jl:565
^{T<:AbstractFloat}(z::Complex{T}, n::Integer) at complex.jl:571
^{T<:Integer}(z::Complex{T}, n::Integer) at complex.jl:573
^{T<:Rational{T<:Integer}}(z::Complex{T}, n::Integer) at rational.jl:363
^(z::Complex, n::Integer) at complex.jl:566
^(x::Rational, n::Integer) at rational.jl:354
^{T<:AbstractFloat}(x::T, y::Rational) at rational.jl:358
^{T<:AbstractFloat}(x::Complex{T}, y::Rational) at rational.jl:359
^(x::Number, y::Rational) at rational.jl:357
^(x::Integer, y::BigInt) at gmp.jl:431
^{T<:Integer}(x::T, p::T) at intfuncs.jl:109
^(x::Number, p::Integer) at intfuncs.jl:110
^(x::Irrational, y::Irrational) at irrationals.jl:72
^{T<:Number}(x::T, y::T) at promotion.jl:238
^(x::Number, y::Number) at promotion.jl:194
^(s::AbstractString, r::Integer) at strings/types.jl:178
^(A::Array{T<:Any,2}, p::Integer) at linalg/dense.jl:172
^(A::Array{T<:Any,2}, p::Number) at linalg/dense.jl:175
^(x, p::Integer) at intfuncs.jl:111

In [40]:
@which 2^3.0

^(x::Number, y::Number) at promotion.jl:194

## Macros