# Álgebra lineal

Enlace recomendado:

[Quantitative Economics with Julia](http://quant-econ.net/_static/pdfs/jl-quant-econ.pdf)

In [10]:
a = [10, 20, 30, 40]

4-element Array{Int64,1}:
 10
 20
 30
 40

In [11]:
ndims(a)

1

In [12]:
size(a)

(4,)

In [13]:
?ndims

search: ndims RoundingMode invdigamma ENDIAN_BOM



```
ndims(A) -> Integer
```

Returns the number of dimensions of `A`


In [14]:
eye(3)

3x3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [15]:
size(ans)

(3,3)

In [16]:
Array{Int64,1} == Vector{Int64}

true

In [17]:
Array{Int64,2} == Matrix{Int64}

true

In [18]:
Array{Int64,3} == Matrix{Int64}

false

In [20]:
a = [10,20,30, 40]

4-element Array{Int64,1}:
 10
 20
 30
 40

In [23]:
b = reshape(a,2,2)

2x2 Array{Int64,2}:
 10  30
 20  40

In [24]:
b[1,1]

10

In [25]:
b[1,1] = 100

100

In [26]:
b

2x2 Array{Int64,2}:
 100  30
  20  40

In [27]:
a = [1. 2. 3. 4.]

1x4 Array{Float64,2}:
 1.0  2.0  3.0  4.0

In [28]:
transpose(a)

4x1 Array{Float64,2}:
 1.0
 2.0
 3.0
 4.0

## Algunos comandos para inicializar arreglos

In [29]:
eye(2)

2x2 Array{Float64,2}:
 1.0  0.0
 0.0  1.0

In [30]:
ones(2,2)

2x2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

In [31]:
fill("bla",2,2)

2x2 Array{ASCIIString,2}:
 "bla"  "bla"
 "bla"  "bla"

In [32]:
a = [10 20; 30 40]

2x2 Array{Int64,2}:
 10  20
 30  40

In [33]:
transpose(a)

2x2 Array{Int64,2}:
 10  30
 20  40

In [34]:
a'

2x2 Array{Int64,2}:
 10  30
 20  40

In [39]:
1:9

1:9

In [40]:
typeof(ans)

UnitRange{Int64}

In [42]:
collect(1:9)

9-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

In [43]:
?collect

search: collect Collections



```
collect(collection)
```

Return an array of all items in a collection. For associative collections, returns Pair{KeyType, ValType}.

```
collect(element_type, collection)
```

Return an array of type `Array{element_type,1}` of all items in a collection.


In [36]:
1:2:9

1:2:9

In [37]:
typeof(ans)

StepRange{Int64,Int64}

In [38]:
a = collect(1:2:9)

5-element Array{Int64,1}:
 1
 3
 5
 7
 9

In [44]:
a = [10 20; 30 40]

2x2 Array{Int64,2}:
 10  20
 30  40

In [45]:
a[:,1]

2-element Array{Int64,1}:
 10
 30

In [46]:
a[1,:]

1x2 Array{Int64,2}:
 10  20

# Métodos sobre arreglos

In [48]:
a = [-1, 0, 1]

3-element Array{Int64,1}:
 -1
  0
  1

In [49]:
length(a)

3

In [50]:
sum(a)

0

In [51]:
mean(a)

0.0

In [53]:
std(a)

1.0

In [54]:
var(a)

1.0

In [55]:
maximum(a)

1

In [56]:
minimum(a)

-1

In [57]:
b = sort(a, rev = true)

3-element Array{Int64,1}:
  1
  0
 -1

In [58]:
?sort

search: sort sort! sortrows sortperm sortcols sortperm! Cshort issorted



```
sort(A, dim, [alg=<algorithm>,] [by=<transform>,] [lt=<comparison>,] [rev=false])
```

Sort a multidimensional array `A` along the given dimension.

```
sort(v, [alg=<algorithm>,] [by=<transform>,] [lt=<comparison>,] [rev=false])
```

Variant of `sort!` that returns a sorted copy of `v` leaving `v` itself unmodified.


In [59]:
a = ones(1,2)

1x2 Array{Float64,2}:
 1.0  1.0

In [60]:
b = ones(2,2)

2x2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

In [61]:
a * b

1x2 Array{Float64,2}:
 2.0  2.0

In [62]:
b * a'

2x1 Array{Float64,2}:
 2.0
 2.0

In [63]:
b * a

LoadError: LoadError: DimensionMismatch("A has dimensions (2,2) but B has dimensions (1,2)")
while loading In[63], in expression starting on line 1

Consideremos el sistema lineal $A X = B$, la solución formal es $X = A^{-1}B$

In [78]:
A = [1. 2; 2 3]

2x2 Array{Float64,2}:
 1.0  2.0
 2.0  3.0

In [79]:
B = ones(2,2)

2x2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

In [80]:
X = inv(A)*B

2x2 Array{Float64,2}:
 -1.0  -1.0
  1.0   1.0

In [81]:
A*X

2x2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

In [82]:
A*X == B

true

In [83]:
a = [1., 2., 4]

3-element Array{Float64,1}:
 1.0
 2.0
 4.0

In [84]:
b = [3.,4.,5]

3-element Array{Float64,1}:
 3.0
 4.0
 5.0

In [85]:
dot(a, b)

31.0

**Tarea** Crea una función que se llame producto punto y realice algo similar a dot

In [87]:
a

3-element Array{Float64,1}:
 1.0
 2.0
 4.0

In [88]:
a * 2

3-element Array{Float64,1}:
 2.0
 4.0
 8.0

In [89]:
a + 2

3-element Array{Float64,1}:
 3.0
 4.0
 6.0

In [90]:
a > 1

LoadError: LoadError: MethodError: `isless` has no method matching isless(::Int64, ::Array{Float64,1})
Closest candidates are:
  isless(::Real, !Matched::AbstractFloat)
  isless(::Real, !Matched::Real)
  isless(::Integer, !Matched::Char)
while loading In[90], in expression starting on line 1

In [91]:
a .> 1

3-element BitArray{1}:
 false
  true
  true

In [92]:
log(a)

3-element Array{Float64,1}:
 0.0     
 0.693147
 1.38629 

In [93]:
A = [1 2; 3 4]

2x2 Array{Int64,2}:
 1  2
 3  4

In [94]:
det(A)

-2.0

In [95]:
trace(A)

5

In [96]:
eigvals(A)

2-element Array{Float64,1}:
 -0.372281
  5.37228 

In [97]:
rank(A)

2